### ISSUE TITLE
White on white submenu text

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-reach#1]
On the demo at https://demo.bizbudding.com/reach-agency/, submenu text is white-on-white:

<img width="372" alt="Screen Shot 2020-06-01 at 10 40 18" src="https://user-images.githubusercontent.com/647669/83391828-5e707f00-a3f4-11ea-9900-85f8e87e8ef8.png">

**Comment by JiveDig** [comment]
Ooh that must have crept in during our update on Friday. I’ll fix this today.
